backend:
  name: github
  repo: becatriz/bloguinho

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - {
          label: "Tag",
          name: "tag",
          widget: "relation",
          collection: "tag",
          value_field: "tag.name",
          search_fields: ["tag.name"],
        }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tag" # Used in routes, e.g., /admin/collections/blog
    label: "Tag" # Used in the UI
    folder: "tag" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Tag", name: "tag", widget: "string" }
